@startuml ActorsAndTransactions
agent "[[#client Referral Status Consumer]]" as Client
agent "[[#server Referral Status Provider]]" as Server
Client -down-> Server : "Retrieve SDOH Referral Status [[pcc-Y6.html PCC-Y6]]"
@enduml
