@startuml
hide footbox
participant "Client" as Client
participant "Server" as Server
activate "Client"
"Client" -> "Server" : 1. Referral Status Query [PCC-Y6]
activate "Server"
"Server" --> "Client" : 2. Referral Status Response [PCC-Y6]
deactivate "Client"
deactivate "Server"
@enduml
